"""Artículos del blog (ES/EN). Edita aquí los textos; después ejecuta: python tools/build.py

Bloques del cuerpo (lista por idioma):
    ("h2", "Título de sección")
    ("p", "Párrafo. Admite enlaces a servicios: {{svc:fascia|texto del enlace}}")
    ("ul", ["punto 1", "punto 2"])
    ("note", "Aviso destacado")
IDs de servicio: wood, fascia, cav, rf, lipo, lymph, postop, relax.
    ('img', archivo, alt)            foto flotante dentro del texto (carpeta site/assets/img/)
    ('imgfull', archivo, alt, pie)   imagen a todo el ancho con pie
    Enlace a otro artículo: {{post:id|texto}}
    Campos opcionales del artículo: "cover" (foto de la tarjeta) y "og_image" (imagen al compartir).

Poner "published": False oculta un artículo sin borrarlo.
# TODO Diana: revisar y confirmar todos los artículos (son una propuesta; salen firmados por ella).
"""

DATE = "2026-10-10"

POSTS = [
    # ------------------------------------------------------------------ 0 (detox, con fotos)
    {
        "id": "detox", "published": True, "date": DATE, "updated": DATE, "read": 7, "services": ["lymph", "relax", "fascia"],
        "cover": "blog/detox/walk.webp", "og_image": "blog/detox/infografia.webp",
        "slug": {"es": "detox-natural-12-habitos", "en": "natural-detox-12-habits"},
        "category": {"es": "Bienestar", "en": "Wellbeing"},
        "title": {"es": "Cómo apoyar tu detox natural: 12 hábitos sencillos de bienestar", "en": "How to support your natural detox: 12 simple wellbeing habits"},
        "desc": {"es": "12 hábitos sencillos para apoyar el bienestar y la eliminación natural del cuerpo: hidratación, movimiento, respiración, calor y más, con sus precauciones.",
                 "en": "12 simple habits to support your body's wellbeing and natural elimination: hydration, movement, breathing, warmth and more, with precautions."},
        "excerpt": {"es": "Tu cuerpo ya sabe depurarse. Estos 12 hábitos de bienestar, desde beber agua hasta caminar junto al mar, pueden acompañarlo.",
                    "en": "Your body already knows how to cleanse itself. These 12 wellbeing habits, from drinking water to walking by the sea, can support it."},
        "body": {
            "es": [
                ("p", "«Detox» es una palabra que se usa mucho, así que empecemos por lo importante: tu cuerpo ya tiene sus propios sistemas para eliminar lo que no necesita (hígado, riñones, pulmones, piel e intestino) y trabajan cada día sin que tengas que hacer nada especial."),
                ("p", "Lo que sí puedes hacer es cuidar los hábitos que acompañan a esos sistemas: hidratarte, moverte, descansar y respirar con calma. Estos 12 hábitos no son tratamientos médicos ni prometen resultados concretos. Son ideas de bienestar para integrar en tu rutina, a tu ritmo y con sentido común."),
                ("note", "Este artículo es informativo y no sustituye el consejo de un profesional de la salud. Si estás embarazada, tienes alguna enfermedad o tomas medicación, consulta con tu médico antes de probar cualquiera de estos hábitos."),
                ("h2", "1. Sauna infrarroja"),
                ("img", "blog/detox/sauna.webp", "Sauna infrarroja con luz cálida en un espacio de bienestar"),
                ("p", "El calor puede ayudar a estimular la sudoración y favorecer la relajación del cuerpo. Mucha gente la disfruta como un momento de pausa y desconexión."),
                ("p", "Bebe agua antes y después, empieza con sesiones cortas y sal si te mareas. Consulta antes con tu médico si estás embarazada, tienes problemas cardiovasculares o tomas medicación."),
                ("h2", "2. Oil pulling"),
                ("img", "blog/detox/oil-pulling.webp", "Mujer sonriendo con un vaso de aceite para hacer oil pulling"),
                ("p", "Consiste en enjuagar la boca con aceite durante unos minutos y puede formar parte de tu rutina de bienestar."),
                ("p", "Es una práctica tradicional con poca evidencia científica detrás, así que no sustituye al cepillado ni a las visitas al dentista. El aceite no se traga: se escupe en la basura, no en el lavabo."),
                ("h2", "3. Calor terapéutico"),
                ("p", "Unas mantas o esterillas de calor suave pueden aportar confort y apoyar el descanso, sobre todo al final del día."),
                ("p", "Usa una temperatura suave, no la apliques sobre heridas o piel irritada y no te duermas con ella encendida."),
                ("h2", "4. Plataforma vibratoria"),
                ("p", "Unos minutos de vibración suave pueden complementar tu rutina de activación corporal."),
                ("p", "En Sculptology, las sesiones de nuestros tratamientos de contorno corporal incluyen 10 minutos de plataforma vibratoria. Si estás embarazada o tienes alguna condición médica, consúltalo antes."),
                ("h2", "5. Agua tibia con limón"),
                ("img", "blog/detox/lemon-water.webp", "Taza de agua tibia con rodajas de limón"),
                ("p", "Empezar el día con hidratación puede apoyar tus hábitos saludables, y el limón le da un toque agradable."),
                ("p", "Si tienes el esmalte sensible, aclara la boca con agua después. No es una bebida milagro: lo que cuenta es hidratarte bien durante todo el día."),
                ("h2", "6. Respiración consciente"),
                ("img", "blog/detox/breathing.webp", "Mujer meditando sentada con las piernas cruzadas"),
                ("p", "La respiración profunda ayuda a bajar el estrés y a conectar con tu cuerpo."),
                ("p", "Prueba con cinco minutos: inspira despacio por la nariz, deja que se llene el abdomen y suelta el aire lentamente. Sin prisas y sin forzar."),
                ("h2", "7. Sol y movimiento"),
                ("img", "blog/detox/walk.webp", "Mujer caminando por un paseo marítimo con vistas a la costa"),
                ("p", "Caminar al aire libre y tomar un poco de sol favorece el bienestar general. En Málaga tienes la suerte de poder hacerlo casi todo el año, por ejemplo paseando junto al mar."),
                ("p", "Evita las horas centrales del día y protégete con crema solar."),
                ("h2", "8. Baño con sales de Epsom"),
                ("img", "blog/detox/bath.webp", "Mujer relajándose en una bañera rodeada de velas"),
                ("p", "Un baño relajante puede ayudarte a desconectar y a aliviar la tensión al final del día."),
                ("p", "Usa agua tibia, no muy caliente, y evítalo si tienes heridas en la piel. Si estás embarazada o tienes problemas cardiovasculares, consulta antes con tu médico."),
                ("h2", "9. Drenaje linfático"),
                ("p", "El masaje suave y rítmico puede ayudar a favorecer la circulación de los fluidos y deja una sensación de ligereza y bienestar."),
                ("p", "Es una de las técnicas que hacemos en el estudio: {{svc:lymph|drenaje linfático en Málaga}}. Consúltanos antes si tienes trombosis o flebitis, insuficiencia cardíaca o renal, fiebre o una infección."),
                ("h2", "10. Compresa de aceite de ricino"),
                ("p", "Aplicada de forma cómoda, puede formar parte de una rutina de autocuidado."),
                ("p", "Es una práctica tradicional con poca evidencia científica. Prueba primero en una zona pequeña de piel, no la uses sobre piel dañada y evítala si estás embarazada."),
                ("h2", "11. Hidratación diaria"),
                ("p", "Beber suficiente agua a lo largo del día apoya el equilibrio natural del organismo. Es probablemente el hábito más sencillo y más importante de la lista."),
                ("p", "Lleva una botella contigo y bebe poco a poco durante el día. Después de un tratamiento corporal, beber agua es especialmente recomendable."),
                ("h2", "12. Cepillado en seco"),
                ("img", "blog/detox/dry-brushing.webp", "Mujer realizando cepillado en seco en la pierna con un cepillo de cerdas naturales"),
                ("p", "Consiste en hacer movimientos suaves hacia el corazón antes de la ducha, con un cepillo de cerdas naturales."),
                ("p", "Hazlo con suavidad: no debe doler ni enrojecer la piel. Evítalo si tienes la piel irritada, con heridas o con alguna afección cutánea."),
                ("h2", "Pequeños hábitos, constancia"),
                ("p", "No hace falta hacer los doce. Elige dos o tres que encajen contigo y mantenlos unas semanas: la constancia pesa más que la intensidad."),
                ("p", "Si quieres un acompañamiento personalizado, en Sculptology adaptamos cada tratamiento a tu cuerpo: {{svc:lymph|drenaje linfático}}, {{svc:fascia|Fascia Blasting}} o {{svc:relax|masaje relajante}}. Y si vienes por primera vez, lee la guía para {{post:first|preparar tu primera sesión}}."),
                ("h2", "Resumen visual"),
                ("p", "Guarda o comparte este resumen de los 12 hábitos:"),
                ("imgfull", "blog/detox/infografia.webp", "Infografía de Sculptology: 12 hábitos sencillos para apoyar tu detox natural", "Los 12 hábitos de un vistazo"),
            ],
            "en": [
                ("p", "“Detox” is a word that gets used a lot, so let's start with what matters: your body already has its own systems for eliminating what it doesn't need (liver, kidneys, lungs, skin and gut), and they work every day without you doing anything special."),
                ("p", "What you can do is look after the habits that go alongside those systems: staying hydrated, moving, resting and breathing calmly. These 12 habits are not medical treatments and do not promise specific results. They are wellbeing ideas to fit into your routine, at your own pace and with common sense."),
                ("note", "This article is for information only and does not replace the advice of a healthcare professional. If you are pregnant, have a medical condition or take medication, please consult your doctor before trying any of these habits."),
                ("h2", "1. Infrared sauna"),
                ("img", "blog/detox/sauna.webp", "Infrared sauna with warm light in a wellness space"),
                ("p", "Heat can help stimulate sweating and encourage the body to relax. Many people enjoy it as a moment to pause and switch off."),
                ("p", "Drink water before and after, start with short sessions and step out if you feel dizzy. Check with your doctor first if you are pregnant, have cardiovascular problems or take medication."),
                ("h2", "2. Oil pulling"),
                ("img", "blog/detox/oil-pulling.webp", "Smiling woman holding a glass of oil for oil pulling"),
                ("p", "This means swishing oil around your mouth for a few minutes, and it can be part of your wellbeing routine."),
                ("p", "It is a traditional practice with little scientific evidence behind it, so it does not replace brushing or dental check-ups. The oil is never swallowed: spit it into the bin, not the sink."),
                ("h2", "3. Therapeutic warmth"),
                ("p", "Gentle heated blankets or mats can bring comfort and support rest, especially at the end of the day."),
                ("p", "Use a gentle temperature, do not apply it over wounds or irritated skin, and do not fall asleep with it switched on."),
                ("h2", "4. Vibration plate"),
                ("p", "A few minutes of gentle vibration can complement your body-activation routine."),
                ("p", "At Sculptology, sessions of our body-contouring treatments include 10 minutes on the vibration plate. If you are pregnant or have a medical condition, check first."),
                ("h2", "5. Warm lemon water"),
                ("img", "blog/detox/lemon-water.webp", "Mug of warm water with lemon slices"),
                ("p", "Starting the day with hydration can support your healthy habits, and the lemon adds a pleasant touch."),
                ("p", "If your enamel is sensitive, rinse your mouth with water afterwards. It is not a miracle drink: what counts is staying well hydrated throughout the day."),
                ("h2", "6. Mindful breathing"),
                ("img", "blog/detox/breathing.webp", "Woman meditating cross-legged"),
                ("p", "Deep breathing helps lower stress and reconnect with your body."),
                ("p", "Try five minutes: breathe in slowly through your nose, let your abdomen fill, and release the air slowly. No rushing and no forcing."),
                ("h2", "7. Sun and movement"),
                ("img", "blog/detox/walk.webp", "Woman walking along a seafront promenade with a view of the coast"),
                ("p", "Walking outdoors and getting a little sun supports general wellbeing. In Málaga you are lucky enough to be able to do it almost all year round, for example by walking along the sea."),
                ("p", "Avoid the middle of the day and protect your skin with sunscreen."),
                ("h2", "8. Epsom salt bath"),
                ("img", "blog/detox/bath.webp", "Woman relaxing in a bathtub surrounded by candles"),
                ("p", "A relaxing bath can help you switch off and ease tension at the end of the day."),
                ("p", "Use warm water, not too hot, and avoid it if you have wounds on your skin. If you are pregnant or have cardiovascular problems, check with your doctor first."),
                ("h2", "9. Lymphatic drainage"),
                ("p", "Gentle, rhythmic massage can help support the circulation of fluids and leaves a feeling of lightness and wellbeing."),
                ("p", "It is one of the techniques we offer at the studio: {{svc:lymph|lymphatic drainage in Málaga}}. Please check with us first if you have thrombosis or phlebitis, heart or kidney failure, a fever or an infection."),
                ("h2", "10. Castor oil pack"),
                ("p", "Applied comfortably, it can be part of a self-care routine."),
                ("p", "It is a traditional practice with little scientific evidence. Test a small area of skin first, do not use it on damaged skin and avoid it if you are pregnant."),
                ("h2", "11. Daily hydration"),
                ("p", "Drinking enough water throughout the day supports the body's natural balance. It is probably the simplest and most important habit on the list."),
                ("p", "Carry a bottle with you and sip steadily through the day. After a body treatment, drinking water is especially recommended."),
                ("h2", "12. Dry brushing"),
                ("img", "blog/detox/dry-brushing.webp", "Woman dry brushing her leg with a natural-bristle brush"),
                ("p", "This means making gentle strokes towards the heart before showering, with a natural-bristle brush."),
                ("p", "Be gentle: it should not hurt or redden the skin. Avoid it if your skin is irritated, broken or affected by a skin condition."),
                ("h2", "Small habits, consistency"),
                ("p", "You do not need to do all twelve. Choose two or three that suit you and keep them up for a few weeks: consistency matters more than intensity."),
                ("p", "If you would like personalised support, at Sculptology we adapt each treatment to your body: {{svc:lymph|lymphatic drainage}}, {{svc:fascia|Fascia Blasting}} or {{svc:relax|relaxing massage}}. And if you are coming for the first time, read our guide to {{post:first|preparing for your first session}}."),
                ("h2", "Visual summary"),
                ("p", "Save or share this summary of the 12 habits:"),
                ("imgfull", "blog/detox/infografia.webp", "Sculptology infographic: 12 simple habits to support your natural detox", "The 12 habits at a glance (infographic in Spanish)"),
            ],
        },
    },
    # ------------------------------------------------------------------ 1
    {
        "id": "fascia", "published": True, "date": DATE, "updated": DATE, "read": 4, "services": ["fascia", "wood", "lymph"],
        "slug": {"es": "fascia-blasting-malaga-que-es", "en": "what-is-fascia-blasting"},
        "category": {"es": "Fascia Blasting", "en": "Fascia Blasting"},
        "title": {"es": "Fascia Blasting en Málaga: qué es y para quién es", "en": "Fascia Blasting in Málaga: what it is and who it is for"},
        "desc": {"es": "Qué es el Fascia Blasting, cómo es una sesión, qué puede aportar y a quién le puede interesar. Una guía clara de Diana Noris, de Sculptology en Málaga.",
                 "en": "What Fascia Blasting is, what a session involves, what it can offer and who it may suit. A clear guide from Diana Noris of Sculptology in Málaga."},
        "excerpt": {"es": "La fascia es el tejido que conecta tu cuerpo. Te explico qué es este trabajo corporal, cómo es una sesión y qué conviene saber antes de empezar.",
                    "en": "Fascia is the tissue that connects your body. Here is what this body work is, what a session involves and what to know before you start."},
        "body": {
            "es": [
                ("p", "La fascia es el tejido conectivo que envuelve y conecta músculos y otras estructuras del cuerpo. Cuando pierde movilidad o está especialmente tensa, algunas personas notan zonas más rígidas, tirantes o con un aspecto irregular. El Fascia Blasting es un trabajo corporal pensado para estimular precisamente esas zonas."),
                ("h2", "¿Qué es el Fascia Blasting?"),
                ("p", "No es un masaje convencional. Es una técnica manual intensa y controlada que utiliza herramientas especialmente diseñadas, como el FasciaBlaster®, para trabajar la fascia de forma progresiva y favorecer una mayor movilidad de los tejidos. En Sculptology es una de nuestras especialidades y la adaptamos a cada cuerpo."),
                ("h2", "¿Qué puede aportar?"),
                ("p", "Depende de cada cuerpo, de la constancia y de cómo responda cada persona. En general, puede ayudar a:"),
                ("ul", ["Favorecer la movilidad y flexibilidad del tejido.", "Trabajar zonas de tensión y rigidez.", "Estimular la circulación local y la sensación de ligereza.", "Mejorar la apariencia de la piel y de las irregularidades asociadas a la celulitis.", "Complementar un programa de remodelación corporal."]),
                ("note", "Los resultados pueden variar de una persona a otra y no pueden garantizarse."),
                ("h2", "¿Cómo es una sesión?"),
                ("p", "Empezamos con una valoración, medidas y fotos. Después, 10 minutos en plataforma vibratoria y un calentamiento de la zona. A continuación se trabaja con la herramienta de forma progresiva, y terminamos con un seguimiento de tu evolución. Solemos recomendar unas 6 sesiones; en la valoración te propongo un plan personalizado."),
                ("h2", "¿Duele? ¿Salen moratones?"),
                ("p", "Es un trabajo intenso, pero la presión se adapta a tu tolerancia. En las primeras sesiones pueden aparecer hematomas leves, que desaparecen en pocos días y suelen ir a menos con cada sesión."),
                ("h2", "¿Cuándo conviene consultarlo antes?"),
                ("p", "Cuéntanos antes de reservar si estás embarazada, si tomas anticoagulantes o tienes problemas de coagulación, si tienes varices o antecedentes de trombosis, o si hay heridas, infecciones o quemaduras solares en la zona. Ante cualquier duda médica, consulta con tu médico."),
                ("p", "Si quieres saber más, mira la página del tratamiento: {{svc:fascia|Fascia Blasting en Málaga}}. También puedes combinarlo con {{svc:wood|maderoterapia}} o {{svc:lymph|drenaje linfático}}."),
            ],
            "en": [
                ("p", "Fascia is the connective tissue that wraps around and links muscles and other structures in the body. When it loses mobility or is particularly tight, some people notice areas that feel stiffer, tighter or uneven. Fascia Blasting is body work designed to stimulate exactly those areas."),
                ("h2", "What is Fascia Blasting?"),
                ("p", "It is not a conventional massage. It is an intense, controlled manual technique that uses specially designed tools, such as the FasciaBlaster®, to work on the fascia progressively and encourage greater mobility of the tissues. At Sculptology it is one of our specialities, and we adapt it to each body."),
                ("h2", "What can it offer?"),
                ("p", "It depends on each body, on consistency and on how each person responds. In general, it can help to:"),
                ("ul", ["Encourage the mobility and flexibility of the tissue.", "Work on areas of tension and stiffness.", "Stimulate local circulation and a feeling of lightness.", "Improve the appearance of the skin and of the irregularities associated with cellulite.", "Complement a body-contouring programme."]),
                ("note", "Results may vary from person to person and cannot be guaranteed."),
                ("h2", "What is a session like?"),
                ("p", "We start with an assessment, measurements and photos. Then 10 minutes on the vibration plate and a warm-up of the area. Next we work with the tool progressively, and we finish by following up on your progress. We usually recommend around 6 sessions; at your assessment I will suggest a personalised plan."),
                ("h2", "Does it hurt? Will I bruise?"),
                ("p", "It is intense work, but the pressure is adapted to your tolerance. Mild bruising can appear in the first sessions; it fades within a few days and usually lessens with each session."),
                ("h2", "When should you check with us first?"),
                ("p", "Tell us before booking if you are pregnant, take anticoagulants or have clotting problems, have varicose veins or a history of thrombosis, or have wounds, infections or sunburn in the area. If you have any medical concerns, please consult your doctor."),
                ("p", "To find out more, see the treatment page: {{svc:fascia|Fascia Blasting in Málaga}}. You can also combine it with {{svc:wood|wood therapy}} or {{svc:lymph|lymphatic drainage}}."),
            ],
        },
    },
    # ------------------------------------------------------------------ 2
    {
        "id": "wood", "published": True, "date": DATE, "updated": DATE, "read": 4, "services": ["wood", "fascia", "lymph"],
        "slug": {"es": "que-es-la-maderoterapia", "en": "what-is-wood-therapy"},
        "category": {"es": "Maderoterapia", "en": "Wood Therapy"},
        "title": {"es": "Maderoterapia: qué es y qué esperar de una sesión", "en": "Wood therapy: what it is and what to expect from a session"},
        "desc": {"es": "Descubre qué es la maderoterapia, para quién es, cómo es una sesión y qué cuidados seguir después. Guía de Sculptology, estudio de estética en Málaga.",
                 "en": "Find out what wood therapy is, who it is for, what a session involves and how to look after yourself afterwards. A guide from Sculptology, aesthetics studio in Málaga."},
        "excerpt": {"es": "Una técnica de masaje de origen colombiano que trabaja el tejido en profundidad. Qué es, cómo es una sesión y qué hacer después.",
                    "en": "A massage technique of Colombian origin that works the tissue deeply. What it is, what a session involves and what to do afterwards."},
        "body": {
            "es": [
                ("p", "La maderoterapia es una técnica de masaje de origen colombiano que usa instrumentos de madera de distintas formas para trabajar el tejido en profundidad y ayudar a moldear la silueta. En Sculptology la combinamos con maniobras manuales adaptadas a cada zona de tu cuerpo."),
                ("h2", "¿Para qué se utiliza?"),
                ("ul", ["Ayudar a moldear y definir la silueta.", "Mejorar el aspecto de la celulitis y la piel de naranja.", "Estimular la circulación y la eliminación de líquidos.", "Tonificar y reafirmar la piel.", "Sensación de ligereza desde la primera sesión."]),
                ("p", "Suele interesar a quienes buscan trabajar retención de líquidos, celulitis, abdomen, cintura, glúteos, piernas o brazos."),
                ("note", "Los resultados pueden variar de una persona a otra."),
                ("h2", "Así es una sesión de maderoterapia"),
                ("p", "Empezamos con una valoración, medidas y fotos. Después, 10 minutos en plataforma vibratoria. A continuación trabajamos con los instrumentos de madera, zona por zona, y terminamos con recomendaciones y seguimiento."),
                ("h2", "¿Duele?"),
                ("p", "Es un masaje intenso, pero la presión se adapta a ti. Es normal notar algo de sensibilidad en las primeras sesiones."),
                ("h2", "¿Cuándo se notan los resultados?"),
                ("p", "Muchas clientas notan menos hinchazón y la piel más lisa desde el principio. Los cambios en la silueta llegan con constancia, y en la valoración te recomiendo la frecuencia que mejor te encaja."),
                ("h2", "Qué hacer después"),
                ("p", "Bebe mucha agua y mantente activa para potenciar el efecto drenante."),
                ("h2", "Cuándo consultarlo antes"),
                ("p", "Avísanos antes de reservar si estás embarazada, tienes varices marcadas o flebitis, tomas anticoagulantes o tienes heridas o infecciones en la piel de la zona. Ante cualquier duda médica, consulta con tu médico."),
                ("p", "Más información, en la página de {{svc:wood|maderoterapia en Málaga}}. Combina muy bien con {{svc:fascia|Fascia Blasting}} y {{svc:lymph|drenaje linfático}}."),
            ],
            "en": [
                ("p", "Wood therapy is a massage technique of Colombian origin that uses wooden instruments of different shapes to work the tissue deeply and help shape the silhouette. At Sculptology we combine it with hands-on techniques adapted to each area of your body."),
                ("h2", "What is it used for?"),
                ("ul", ["Helping to shape and define the silhouette.", "Improving the look of cellulite and orange-peel skin.", "Stimulating circulation and the elimination of fluids.", "Toning and firming the skin.", "A feeling of lightness from the very first session."]),
                ("p", "It tends to appeal to people who want to work on fluid retention, cellulite, abdomen, waist, glutes, legs or arms."),
                ("note", "Results may vary from person to person."),
                ("h2", "What a wood therapy session is like"),
                ("p", "We start with an assessment, measurements and photos. Then 10 minutes on the vibration plate. Next we work with the wooden instruments, area by area, and finish with recommendations and follow-up."),
                ("h2", "Does it hurt?"),
                ("p", "It is an intense massage, but the pressure is adapted to you. Some tenderness in the first sessions is normal."),
                ("h2", "When will I see results?"),
                ("p", "Many clients notice less swelling and smoother skin from the start. Changes to the silhouette come with consistency, and at your assessment I will recommend the frequency that suits you best."),
                ("h2", "What to do afterwards"),
                ("p", "Drink plenty of water and stay active to boost the draining effect."),
                ("h2", "When to check with us first"),
                ("p", "Let us know before booking if you are pregnant, have pronounced varicose veins or phlebitis, take anticoagulants, or have wounds or skin infections in the area. If you have any medical concerns, please consult your doctor."),
                ("p", "For more information, see the page on {{svc:wood|wood therapy in Málaga}}. It combines very well with {{svc:fascia|Fascia Blasting}} and {{svc:lymph|lymphatic drainage}}."),
            ],
        },
    },
    # ------------------------------------------------------------------ 3
    {
        "id": "cav-rf", "published": True, "date": DATE, "updated": DATE, "read": 4, "services": ["cav", "rf", "lipo"],
        "slug": {"es": "cavitacion-vs-radiofrecuencia", "en": "cavitation-vs-radiofrequency"},
        "category": {"es": "Contorno corporal", "en": "Body contouring"},
        "title": {"es": "Cavitación y radiofrecuencia: diferencias y cómo se complementan", "en": "Cavitation and radiofrequency: the differences and how they work together"},
        "desc": {"es": "¿Cavitación o radiofrecuencia? Te explico en qué se diferencian, para qué sirve cada una y por qué suelen combinarse en un plan de contorno corporal.",
                 "en": "Cavitation or radiofrequency? Here is how they differ, what each is for and why they are often combined in a body-contouring plan."},
        "excerpt": {"es": "Dos tratamientos no invasivos que se confunden a menudo. Qué hace cada uno y por qué funcionan tan bien juntos.",
                    "en": "Two non-invasive treatments that are often confused. What each does and why they work so well together."},
        "body": {
            "es": [
                ("p", "La cavitación y la radiofrecuencia son dos tratamientos no invasivos que se nombran juntos con frecuencia, pero actúan de forma distinta. Conocer la diferencia te ayuda a elegir y a entender por qué en Sculptology solemos combinarlos."),
                ("h2", "Cavitación: ultrasonidos para zonas rebeldes"),
                ("p", "Usa ultrasonidos de baja frecuencia para actuar sobre la grasa localizada y ayudar a remodelar el contorno. Se aplica con gel conductor, sin agujas ni cirugía y sin tiempo de recuperación. Suele elegirse para abdomen, cintura, flancos y piernas."),
                ("h2", "Radiofrecuencia: calor controlado para la firmeza"),
                ("p", "Genera un calor controlado en las capas profundas de la piel para estimular el colágeno y la elastina. Ayuda a mejorar el aspecto de la flacidez y deja la piel más firme y tersa. Es una sensación agradable, como un masaje caliente."),
                ("h2", "Entonces, ¿cuál elijo?"),
                ("ul", ["Si tu objetivo es remodelar una zona concreta con grasa localizada: cavitación.", "Si lo que te preocupa es la firmeza de la piel, por ejemplo tras cambios de peso: radiofrecuencia.", "Si quieres ambas cosas: se combinan muy bien, y a menudo se completan con {{svc:lipo|lipoláser}}."]),
                ("p", "En la valoración vemos tu caso y te propongo el plan más adecuado."),
                ("h2", "Importante: no son para perder peso"),
                ("p", "La cavitación no es un tratamiento para adelgazar, sino para moldear zonas concretas, y funciona mejor acompañada de hábitos saludables. Los resultados de la radiofrecuencia son progresivos, por eso se trabaja en serie de sesiones."),
                ("note", "Los resultados pueden variar de una persona a otra."),
                ("h2", "Antes de tu sesión"),
                ("p", "Bebe mucha agua antes y después, y evita el alcohol y las comidas muy grasas en los días del tratamiento. Avísanos si estás embarazada o en lactancia, si llevas marcapasos, implantes metálicos o prótesis en la zona, si tienes enfermedades hepáticas o renales o cáncer activo. Ante cualquier duda médica, consulta con tu médico."),
                ("p", "Puedes ver los detalles de cada una en las páginas de {{svc:cav|cavitación}} y {{svc:rf|radiofrecuencia}}."),
            ],
            "en": [
                ("p", "Cavitation and radiofrequency are two non-invasive treatments that are often mentioned together, but they work in different ways. Knowing the difference helps you choose, and explains why at Sculptology we usually combine them."),
                ("h2", "Cavitation: ultrasound for stubborn areas"),
                ("p", "It uses low-frequency ultrasound to target localised fat and help reshape the contours. It is applied with conductive gel, with no needles, no surgery and no downtime. It is usually chosen for the abdomen, waist, flanks and legs."),
                ("h2", "Radiofrequency: controlled heat for firmness"),
                ("p", "It produces controlled heat in the deeper layers of the skin to stimulate collagen and elastin. It helps improve the look of loose skin and leaves it firmer and smoother. It feels pleasant, like a hot massage."),
                ("h2", "So which should I choose?"),
                ("ul", ["If your goal is to reshape a specific area with localised fat: cavitation.", "If your concern is the firmness of the skin, for example after weight changes: radiofrequency.", "If you want both: they combine very well, and are often completed with {{svc:lipo|lipo laser}}."]),
                ("p", "At your assessment we look at your case and I will suggest the most suitable plan."),
                ("h2", "Important: they are not for weight loss"),
                ("p", "Cavitation is not a weight-loss treatment; it is for shaping specific areas, and it works best alongside healthy habits. Radiofrequency results build up gradually, which is why we work in a series of sessions."),
                ("note", "Results may vary from person to person."),
                ("h2", "Before your session"),
                ("p", "Drink plenty of water before and after, and avoid alcohol and very fatty meals on the days of your treatment. Let us know if you are pregnant or breastfeeding, have a pacemaker, metal implants or a prosthesis in the area, have liver or kidney disease or active cancer. If you have any medical concerns, please consult your doctor."),
                ("p", "You can see the details of each on the pages for {{svc:cav|cavitation}} and {{svc:rf|radiofrequency}}."),
            ],
        },
    },
    # ------------------------------------------------------------------ 4
    {
        "id": "postop", "published": True, "date": DATE, "updated": DATE, "read": 4, "services": ["postop", "lymph"],
        "slug": {"es": "masaje-postoperatorio-cuando-empezar", "en": "post-op-massage-when-to-start"},
        "category": {"es": "Postoperatorio", "en": "Post-op care"},
        "title": {"es": "Masaje postoperatorio: cuándo empezar y qué debes saber", "en": "Post-op massage: when to start and what you should know"},
        "desc": {"es": "Masajes postoperatorios tras una cirugía estética: cuándo empezar, qué incluyen y qué debes consultar con tu cirujano. Guía de Sculptology en Málaga.",
                 "en": "Post-operative massage after cosmetic surgery: when to start, what it involves and what to check with your surgeon. A guide from Sculptology in Málaga."},
        "excerpt": {"es": "Después de una cirugía estética, cuidarte importa. Cuándo empezar, qué incluye el masaje y qué debes comentar con tu cirujano.",
                    "en": "After cosmetic surgery, looking after yourself matters. When to start, what the massage includes and what to discuss with your surgeon."},
        "body": {
            "es": [
                ("p", "Tras una cirugía estética, como liposucción, lipoescultura, abdominoplastia, BBL o cirugía de mamas, muchas personas buscan un acompañamiento para su recuperación. Los masajes postoperatorios combinan drenaje linfático manual con técnicas específicas para reducir la inflamación, prevenir la fibrosis y ayudarte a recuperarte mejor."),
                ("h2", "¿Cuándo empezar?"),
                ("p", "Cuando tu cirujano lo autorice, normalmente en los primeros días o semanas. Es imprescindible contar con su autorización: cada cirugía y cada recuperación son distintas, y es él quien conoce tu caso."),
                ("h2", "¿Qué puede aportar?"),
                ("ul", ["Ayudar a reducir la inflamación y el edema.", "Prevenir y tratar la fibrosis y los endurecimientos.", "Favorecer una buena cicatrización.", "Ayudar a que el resultado de tu cirugía se vea más uniforme.", "Acompañamiento cercano en una etapa delicada."]),
                ("note", "Los resultados pueden variar de una persona a otra y dependen de tu cirugía y de tu evolución."),
                ("h2", "Cómo es una sesión"),
                ("p", "Empezamos revisando tu cirugía y las indicaciones médicas que te dieron. Después hacemos drenaje y técnicas específicas para la fibrosis, y terminamos con pautas de cuidado en casa. Trae tus indicaciones médicas y tu faja a cada sesión."),
                ("h2", "¿Cuántas sesiones necesito?"),
                ("p", "Depende de la cirugía y de cómo evoluciones. Te propongo un plan personalizado en la primera sesión."),
                ("h2", "Cuándo debes consultar antes con tu médico"),
                ("p", "Si tu cirujano aún no ha autorizado los masajes, si tienes fiebre o signos de infección, o si sospechas una trombosis, consulta antes con tu médico. Ante cualquier duda médica, consulta con tu médico."),
                ("p", "Más información en la página de {{svc:postop|masajes postoperatorios en Málaga}}. El {{svc:lymph|drenaje linfático}} también puede ayudarte a sentirte más ligera."),
            ],
            "en": [
                ("p", "After cosmetic surgery, such as liposuction, liposculpture, a tummy tuck, BBL or breast surgery, many people look for support during their recovery. Post-operative massages combine manual lymphatic drainage with specific techniques to reduce inflammation, prevent fibrosis and help you recover better."),
                ("h2", "When should you start?"),
                ("p", "Once your surgeon gives the go-ahead, usually in the first days or weeks. Their authorisation is essential: every surgery and every recovery is different, and they are the one who knows your case."),
                ("h2", "What can it offer?"),
                ("ul", ["Helping to reduce inflammation and oedema.", "Preventing and treating fibrosis and hardened areas.", "Supporting good healing.", "Helping your surgical result look more even.", "Close support during a delicate stage."]),
                ("note", "Results may vary from person to person and depend on your surgery and how you heal."),
                ("h2", "What a session is like"),
                ("p", "We start by reviewing your surgery and the medical instructions you were given. Then we do drainage and specific techniques for fibrosis, and finish with aftercare guidance for home. Please bring your medical instructions and your compression garment to every session."),
                ("h2", "How many sessions do I need?"),
                ("p", "It depends on the surgery and how you are healing. I will suggest a personalised plan at your first session."),
                ("h2", "When to speak to your doctor first"),
                ("p", "If your surgeon has not yet authorised massage, if you have a fever or signs of infection, or if you suspect a thrombosis, please speak to your doctor first. If you have any medical concerns, please consult your doctor."),
                ("p", "More information on the page for {{svc:postop|post-op massage in Málaga}}. {{svc:lymph|Lymphatic drainage}} can also help you feel lighter."),
            ],
        },
    },
    # ------------------------------------------------------------------ 5
    {
        "id": "first", "published": True, "date": DATE, "updated": DATE, "read": 3, "services": ["fascia", "cav", "lymph"],
        "slug": {"es": "preparar-tu-primera-sesion", "en": "prepare-for-your-first-session"},
        "category": {"es": "Primera visita", "en": "First visit"},
        "title": {"es": "Cómo preparar tu primera sesión en Sculptology", "en": "How to prepare for your first session at Sculptology"},
        "desc": {"es": "Cómo reservar, qué incluye tu primera sesión, qué cuidados seguir antes y después y qué contarnos. Todo lo que necesitas saber para tu primera visita.",
                 "en": "How to book, what your first session includes, how to look after yourself before and after, and what to tell us. Everything you need for your first visit."},
        "excerpt": {"es": "Cómo reservar, qué incluye cada sesión y qué hacer antes y después para sentirte cómoda desde el primer día.",
                    "en": "How to book, what every session includes and what to do before and after so you feel comfortable from day one."},
        "body": {
            "es": [
                ("p", "Si es tu primera vez en Sculptology, esto es lo que conviene saber para que llegues tranquila y aproveches al máximo tu sesión."),
                ("h2", "1. Reserva online"),
                ("p", "Trabajamos solo con cita previa, en un estudio privado en Málaga Centro. Puedes elegir tratamiento, día y hora en un minuto desde nuestra agenda online. Abrimos de martes a domingo, de 11:00 a 20:00; los lunes estamos cerrados. Si tienes dudas antes de reservar, escríbenos por WhatsApp."),
                ("h2", "2. Qué incluye cada sesión"),
                ("ul", ["10 minutos de plataforma vibratoria.", "Medidas corporales y fotos de antes y después.", "Seguimiento personalizado de tu progreso."]),
                ("h2", "3. Cuéntanos tu situación"),
                ("p", "Antes de empezar, cuéntanos si estás embarazada o en lactancia, si tomas anticoagulantes u otra medicación, si has tenido una cirugía reciente o si tienes alguna condición médica. Es la forma de adaptar el tratamiento a ti con seguridad. Ante cualquier duda médica, consulta con tu médico."),
                ("h2", "4. Antes y después"),
                ("p", "Bebe mucha agua antes y después del tratamiento. Si vas a hacerte cavitación, evita el alcohol y las comidas muy grasas en los días del tratamiento. Después, mantente activa para potenciar el efecto drenante."),
                ("h2", "5. Constancia y expectativas"),
                ("p", "Cada cuerpo responde de manera diferente. Por eso, en la valoración te propongo un plan según tu objetivo y la frecuencia que mejor te encaje. Los resultados pueden variar de una persona a otra."),
                ("p", "¿No sabes por dónde empezar? Echa un vistazo a nuestros tratamientos: {{svc:fascia|Fascia Blasting}}, {{svc:cav|cavitación}} o {{svc:lymph|drenaje linfático}}."),
            ],
            "en": [
                ("p", "If it is your first time at Sculptology, here is what is worth knowing so you arrive relaxed and make the most of your session."),
                ("h2", "1. Book online"),
                ("p", "We work by appointment only, in a private studio in central Málaga. You can choose your treatment, day and time in a minute from our online booking page. We are open Tuesday to Sunday, 11:00 to 20:00, and closed on Mondays. If you have questions before booking, message us on WhatsApp."),
                ("h2", "2. What every session includes"),
                ("ul", ["10 minutes on the vibration plate.", "Body measurements and before-and-after photos.", "Personalised follow-up of your progress."]),
                ("h2", "3. Tell us about your situation"),
                ("p", "Before we start, tell us if you are pregnant or breastfeeding, take anticoagulants or other medication, have had recent surgery or have any medical condition. It is how we adapt the treatment to you safely. If you have any medical concerns, please consult your doctor."),
                ("h2", "4. Before and after"),
                ("p", "Drink plenty of water before and after your treatment. If you are having cavitation, avoid alcohol and very fatty meals on the days of your treatment. Afterwards, stay active to boost the draining effect."),
                ("h2", "5. Consistency and expectations"),
                ("p", "Every body responds differently. That is why, at your assessment, I suggest a plan based on your goal and the frequency that suits you best. Results may vary from person to person."),
                ("p", "Not sure where to start? Have a look at our treatments: {{svc:fascia|Fascia Blasting}}, {{svc:cav|cavitation}} or {{svc:lymph|lymphatic drainage}}."),
            ],
        },
    },
]
