"""Textos de interfaz ES/EN (portada y páginas de servicio). Inglés británico (en_GB)."""

PHONE_TXT, PHONE_INT, WA_NUM = "+34 657 780 333", "+34657780333", "34657780333"

T = {
 "es": {
  "lang": "es", "locale": "es_ES", "path": "/", "other": "/en/",
  "title": "Sculptology Málaga | Maderoterapia, Fascia Blasting y Drenaje Linfático",
  "desc": "Estudio de estética y bienestar en Málaga Centro: maderoterapia, Fascia Blasting, cavitación, radiofrecuencia y drenaje linfático. Atención VIP en español e inglés.",
  "skip": "Saltar al contenido",
  "nav": [("about", "Sobre mí"), ("services", "Servicios"), ("results", "Resultados"), ("reviews", "Opiniones"), ("contact", "Contacto")],
  "book": "Reserva tu cita",
  "wa_msg": "Hola, tengo una duda sobre los tratamientos de Sculptology.",
  "wa_ghost": "¿Dudas? WhatsApp", "wa_float": "¿Dudas? Escríbenos por WhatsApp", "wa_pill": "¿Dudas?",
  "wa_link": "¿Tienes dudas? Escríbenos por WhatsApp",
  "appt": "Solo con cita previa", "hero_note": "Estudio privado · Solo con cita previa",
  "eyebrow": "Málaga Centro · Estudio de estética y bienestar",
  "h1": "El arte de <em>moldear</em> tu cuerpo", "en_sub": "The art of sculpting your body",
  "lead": "Maderoterapia, Fascia Blasting, cavitación, radiofrecuencia y drenaje linfático con atención VIP, tiempo y un plan pensado para ti. Atención en español e inglés.",
  "see_results": "Ver resultados",
  "badges": [("20+", "Años de experiencia"), ("EE. UU.", "Formación profesional"), ("ES · EN", "Completamente bilingüe"), ("VIP", "Atención personalizada")],
  "about_k": "Sobre Sculptology", "about_h": "Más que estética, es bienestar <em>real.</em>",
  "about_p": [
   "Soy <strong>Diana Noris</strong>, fundadora de Sculptology. Soy esteticista profesional formada en los Estados Unidos, con más de 20 años de experiencia en la industria de la estética y el bienestar. Me especializo en maderoterapia, Fascia Blasting, cavitación, radiofrecuencia, drenaje linfático, masajes postoperatorios y eye therapy. En mi estudio en Málaga ofrezco una experiencia personalizada, exclusiva y de alto nivel, donde cada clienta recibe atención VIP, tiempo, dedicación y un plan pensado para lograr los mejores resultados posibles.",
   "Soy completamente bilingüe en inglés y español. Mi prioridad es que te sientas cómoda, cuidada y 100% satisfecha con tu tratamiento. Tengo numerosas reseñas de cinco estrellas y trabajo para ayudarte a alcanzar tus objetivos corporales con resultados visibles y reales.",
  ],
  "signature": "Tu cuerpo, en las mejores manos.",
  "pillars": [("lotus", "20+ años", "de experiencia"), ("cap", "Formación", "en Estados Unidos"), ("chat", "Bilingüe", "Español & English"), ("gem", "Atención", "VIP")],
  "tag": ("Diana Noris", "Fundadora"),
  "portrait_alt": "Diana Noris, fundadora de Sculptology, esteticista profesional en Málaga",
  "svc_k": "Servicios", "svc_h": "Tratamientos de <em>contorno corporal</em> y bienestar",
  "svc_p": "Cada plan se diseña según tu cuerpo y tus objetivos, en un estudio privado en el centro de Málaga. Pulsa un tratamiento para ver cómo es, qué incluye y sus precios.",
  "svc_more": "Ver tratamiento",
  "res_k": "Resultados reales", "res_h": "Antes y <em>después</em>",
  "res_p": "Fotos reales de clientes de Sculptology y del estudio anterior de Diana. Toca una foto para ampliarla.",
  "disclaimer": "Los resultados pueden variar de una persona a otra.",
  "rev_k": "Opiniones de clientes", "rev_h": "Lo que dicen <em>nuestras clientas</em>",
  "rev_p": "Opiniones reales de 5 estrellas de clientes del anterior estudio de Diana en EE. UU.",
  "rev_badge": "5.0 · 13 opiniones de 5 estrellas",
  "sculpt_line": "Esculpe • Tonifica • Drena • Siéntete tu mejor versión", "sculpt_script": "El arte de moldear tu cuerpo.",
  "con_k": "Contacto", "con_h": "Ven a <em>conocernos</em>",
  "con_p": "Estudio privado en el centro de Málaga · Solo con cita previa. Atención en español e inglés.",
  "loc": "Ubicación · Location", "addr": "Calle Santa Lucía 11 · Málaga Centro<br>Piso 1º · Puerta 7",
  "book_l": "Reservas · Booking", "book_p": "Elige tratamiento, día y hora en un minuto.",
  "wa_l": "Dudas · WhatsApp", "wa_big": "Escríbenos", "wa_small": "+34 657 780 333 · Respondemos por mensaje",
  "hours_l": "Horario · Hours", "days": "Martes a domingo", "days_en": "Tuesday to Sunday",
  "hours": "11:00–20:00", "hours_alt": "11:00 AM – 8:00 PM", "closed": "Lunes cerrado · Solo con cita previa",
  "cta_h": "Tu mejor versión empieza aquí",
  "cta_p": "Reserva online en un minuto: eliges tratamiento, día y hora. ¿Tienes alguna duda? Escríbenos por WhatsApp.",
  "map_t": "Mapa: Sculptology, Calle Santa Lucía 11, Málaga",
  "f_rights": "Todos los derechos reservados.", "f_tag": "El arte de moldear tu cuerpo",
  "before": "Antes", "after": "Después", "front": "Frontal", "side": "Lateral", "back": "Posterior",
  "wa_aria": "¿Dudas? Escríbenos por WhatsApp", "menu": "Menú",
 },
 "en": {
  "lang": "en", "locale": "en_GB", "path": "/en/", "other": "/",
  "title": "Sculptology Málaga | Wood Therapy, Fascia Blasting & Lymphatic Drainage",
  "desc": "Body contouring and wellness studio in central Málaga: wood therapy, Fascia Blasting, cavitation, radiofrequency and drainage. VIP care in English and Spanish.",
  "skip": "Skip to content",
  "nav": [("about", "About"), ("services", "Services"), ("results", "Results"), ("reviews", "Reviews"), ("contact", "Contact")],
  "book": "Book now",
  "wa_msg": "Hi, I have a question about Sculptology's treatments.",
  "wa_ghost": "Questions? WhatsApp", "wa_float": "Questions? Message us on WhatsApp", "wa_pill": "Questions?",
  "wa_link": "Any questions? Message us on WhatsApp",
  "appt": "By appointment only", "hero_note": "Private studio · By appointment only",
  "eyebrow": "Central Málaga · Aesthetics & wellness studio",
  "h1": "The art of <em>sculpting</em> your body", "en_sub": "El arte de moldear tu cuerpo",
  "lead": "Wood therapy, Fascia Blasting, cavitation, radiofrequency and lymphatic drainage with VIP attention, time and a plan made for you. Services in English and Spanish.",
  "see_results": "See results",
  "badges": [("20+", "Years of experience"), ("USA", "Professional training"), ("EN · ES", "Fully bilingual"), ("VIP", "Personalised care")],
  "about_k": "About Sculptology", "about_h": "More than aesthetics, it's <em>real</em> wellbeing.",
  "about_p": [
   "I'm <strong>Diana Noris</strong>, founder of Sculptology. I'm a professional aesthetician trained in the United States, with more than 20 years of experience in the aesthetics and wellness industry. I specialise in wood therapy, Fascia Blasting, cavitation, radiofrequency, lymphatic drainage, post-operative massage and eye therapy. In my Málaga studio I offer a personalised, exclusive, high-end experience where every client receives VIP attention, time, dedication and a plan designed to achieve the best possible results.",
   "I'm completely bilingual in English and Spanish. My priority is that you feel comfortable, cared for and 100% satisfied with your treatment. I have numerous five-star reviews and I work to help you reach your body goals with visible, real results.",
  ],
  "signature": "Your body, in the best hands.",
  "pillars": [("lotus", "20+ years", "of experience"), ("cap", "Training", "in the United States"), ("chat", "Bilingual", "English & Español"), ("gem", "VIP", "care")],
  "tag": ("Diana Noris", "Founder"),
  "portrait_alt": "Diana Noris, founder of Sculptology, professional aesthetician in Málaga",
  "svc_k": "Services", "svc_h": "<em>Body contouring</em> and wellness treatments",
  "svc_p": "Every plan is designed around your body and your goals, in a private studio in the centre of Málaga. Tap a treatment to see what it involves, what's included and its prices.",
  "svc_more": "View treatment",
  "res_k": "Real results", "res_h": "Before & <em>after</em>",
  "res_p": "Real photos of Sculptology clients and of Diana's previous studio. Tap a photo to enlarge it.",
  "disclaimer": "Results may vary from person to person.",
  "rev_k": "Client reviews", "rev_h": "What <em>our clients</em> say",
  "rev_p": "Real 5-star feedback from Diana's previous U.S. studio.",
  "rev_badge": "5.0 · 13 five-star reviews",
  "sculpt_line": "Sculpt • Tone • Drain • Feel your best", "sculpt_script": "El arte de moldear tu cuerpo.",
  "con_k": "Contact", "con_h": "Come and <em>meet us</em>",
  "con_p": "Private studio in the centre of Málaga · By appointment only. Services in English and Spanish.",
  "loc": "Location · Ubicación", "addr": "Calle Santa Lucía 11 · Málaga Centro<br>1st floor · Door 7",
  "book_l": "Booking · Reservas", "book_p": "Choose your treatment, day and time in a minute.",
  "wa_l": "Questions · WhatsApp", "wa_big": "Message us", "wa_small": "+34 657 780 333 · We reply by message",
  "hours_l": "Hours · Horario", "days": "Tuesday to Sunday", "days_en": "Martes a domingo",
  "hours": "11:00 AM – 8:00 PM", "hours_alt": "11:00–20:00", "closed": "Closed on Mondays · By appointment only",
  "cta_h": "Your best self starts here",
  "cta_p": "Book online in a minute: choose your treatment, day and time. Any questions? Message us on WhatsApp.",
  "map_t": "Map: Sculptology, Calle Santa Lucía 11, Málaga",
  "f_rights": "All rights reserved.", "f_tag": "The art of sculpting your body",
  "before": "Before", "after": "After", "front": "Front", "side": "Side", "back": "Back",
  "wa_aria": "Questions? Message us on WhatsApp", "menu": "Menu",
 },
}

# Páginas de servicio
S = {
 "es": {
  "kicker": "Tratamiento", "home": "Inicio", "services": "Servicios",
  "what": "¿Qué es?", "benefits": "Beneficios", "session": "Cómo es la sesión", "prices": "Precios",
  "includes": "Qué incluye cada sesión", "photos": "Fotos del tratamiento", "ba": "Antes y después",
  "faq": "Preguntas frecuentes", "consult": "Antes de reservar, consúltanos si…", "others": "Otros tratamientos",
  "review": "Opinión de una clienta",
  "price_tbc": "Consultar precio al reservar",
  "med": "Ante cualquier duda médica, consulta con tu médico.",
  "may_vary": "Los resultados pueden variar de una persona a otra.",
  "combined": "Resultados de planes combinados que incluyen {name}. Los resultados pueden variar.",
  "soon": "Muy pronto: fotos reales de este tratamiento en Sculptology",
  "title": "{name} en Málaga | Sculptology", "step": "Paso",
 },
 "en": {
  "kicker": "Treatment", "home": "Home", "services": "Services",
  "what": "What is it?", "benefits": "Benefits", "session": "What a session is like", "prices": "Prices",
  "includes": "What every session includes", "photos": "Treatment photos", "ba": "Before & after",
  "faq": "Frequently asked questions", "consult": "Before you book, talk to us if…", "others": "Other treatments",
  "review": "What a client says",
  "price_tbc": "Please ask about the price when booking",
  "med": "If you have any medical concerns, please consult your doctor.",
  "may_vary": "Results may vary from person to person.",
  "combined": "Results from combined plans that include {name}. Results may vary.",
  "soon": "Coming soon: real photos of this treatment at Sculptology",
  "title": "{name} in Málaga | Sculptology", "step": "Step",
 },
}
